config/routes.rb
Tsubasa::Application.routes.draw do

  resources :special_attacks, :only => [:index, :show]

  resources :level_data

  resources :players, :only => [:index, :show]

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :player
  
  validates_presence_of :grade_id
  validates_uniqueness_of :grade_id
end

app/models/level_datum.rb
class LevelDatum < ActiveRecord::Base
  belongs_to :player, :counter_cache => true
  
  default_scope :order => ["player_id", "level"]
  
  validates_presence_of :player_id, :level
  validates_uniqueness_of :level, :scope => [:player_id]
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :special_attack_slots, :primary_key => "player_id", :foreign_key => "player_id"
  has_many :special_attacks, :through => :special_attack_slots, :primary_key => "player_id", :foreign_key => "player_id"
  has_many :level_datum, :primary_key => "player_id", :foreign_key => "player_id"
  has_one :max_level, :class_name => "LevelDatum", :conditions => {:next_exp => 0}, :primary_key => "player_id", :foreign_key => "player_id"
  has_one :grade, :primary_key => "grade_id", :foreign_key => "grade_id"
  has_one :teams, :primary_key => "player_team_id", :foreign_key => "team_id"
  
  validates_presence_of :player_id
  validates_uniqueness_of :player_id
  
  default_scope :order => "player_id"
  
  def self.with_grade(grade)
    if (grade.nil?)
      all
    else
      find_all_by_grade_id(grade)
    end
  end
    
  def to_param
    player_id
  end
end

app/models/special_attack.rb
class SpecialAttack < ActiveRecord::Base
  has_many :special_attack_slots, :primary_key => "special_attack_id", :foreign_key => "special_attack_id"
  has_many :players, :through => :special_attack_slots, :primary_key => "special_attack_id", :foreign_key => "special_attack_id"
  
  validates_presence_of :special_attack_id
  validates_uniqueness_of :special_attack_id

  default_scope :order => "special_attack_id"
  
  def self.with_same_name
    where :name => self.name, :conditions => ["id != ?", self.id]
  end
  
  def to_param
    special_attack_id
  end
end

app/models/special_attack_slot.rb
class SpecialAttackSlot < ActiveRecord::Base
  belongs_to :player, :primary_key => "player_id", :foreign_key => "player_id"
  belongs_to :special_attack, :primary_key => "special_attack_id", :foreign_key => "special_attack_id"
  
  delegate :name, :to => :special_attacks
end

app/models/teams.rb
class Teams < ActiveRecord::Base
  belongs_to :player, :foreign_key => "player_team_id"
  
  validates_presence_of :team_id
  validates_uniqueness_of :team_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/level_data_controller.rb
class LevelDataController < ApplicationController
  # GET /level_data
  # GET /level_data.json
  def index
    @level_data = LevelDatum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @level_data }
    end
  end

  # GET /level_data/1
  # GET /level_data/1.json
  def show
    @level_datum = LevelDatum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @level_datum }
    end
  end

  # GET /level_data/new
  # GET /level_data/new.json
  def new
    @level_datum = LevelDatum.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @level_datum }
    end
  end

  # GET /level_data/1/edit
  def edit
    @level_datum = LevelDatum.find(params[:id])
  end

  # POST /level_data
  # POST /level_data.json
  def create
    @level_datum = LevelDatum.new(params[:level_datum])

    respond_to do |format|
      if @level_datum.save
        format.html { redirect_to @level_datum, notice: 'Level datum was successfully created.' }
        format.json { render json: @level_datum, status: :created, location: @level_datum }
      else
        format.html { render action: "new" }
        format.json { render json: @level_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /level_data/1
  # PUT /level_data/1.json
  def update
    @level_datum = LevelDatum.find(params[:id])

    respond_to do |format|
      if @level_datum.update_attributes(params[:level_datum])
        format.html { redirect_to @level_datum, notice: 'Level datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @level_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /level_data/1
  # DELETE /level_data/1.json
  def destroy
    @level_datum = LevelDatum.find(params[:id])
    @level_datum.destroy

    respond_to do |format|
      format.html { redirect_to level_data_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.includes(:max_level, :teams, :grade).with_grade(params[:grade])
    @levelcount = LevelDatum.count
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find_by_player_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find_by_player_id(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find_by_player_id(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find_by_player_id(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/special_attacks_controller.rb
class SpecialAttacksController < ApplicationController
  def index
    @special_attack = SpecialAttack.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @special_attack }
    end
  end

  def show
    @special_attack = SpecialAttack.includes({:players => [:teams, :grade]}).find_by_special_attack_id(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @special_attack }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/level_data_helper.rb
module LevelDataHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/special_attack_helper.rb
module SpecialAttackHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tsubasa</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/level_data/_form.html.haml
= form_for @level_datum do |f|
  -if @level_datum.errors.any?
    #error_explanation
      %h2= "#{pluralize(@level_datum.errors.count, "error")} prohibited this level_datum from being saved:"
      %ul
        - @level_datum.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :player_id
    = f.number_field :player_id
  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :next_exp
    = f.number_field :next_exp
  .field
    = f.label :shoot
    = f.number_field :shoot
  .field
    = f.label :dribble
    = f.number_field :dribble
  .field
    = f.label :pass
    = f.number_field :pass
  .field
    = f.label :block
    = f.number_field :block
  .field
    = f.label :tackle
    = f.number_field :tackle
  .field
    = f.label :cut
    = f.number_field :cut
  .field
    = f.label :speed
    = f.number_field :speed
  .field
    = f.label :power
    = f.number_field :power
  .field
    = f.label :technique
    = f.number_field :technique
  .field
    = f.label :stamina
    = f.number_field :stamina
  .field
    = f.label :catching
    = f.number_field :catching
  .field
    = f.label :punching
    = f.number_field :punching
  .field
    = f.label :offense
    = f.number_field :offense
  .field
    = f.label :defense
    = f.number_field :defense
  .field
    = f.label :total_point
    = f.number_field :total_point
  .actions
    = f.submit 'Save'

app/views/level_data/edit.html.haml
%h1 Editing level_datum

= render 'form'

= link_to 'Show', @level_datum
\|
= link_to 'Back', level_data_path

app/views/level_data/index.html.haml
%h1 Listing level_data

%table
  %tr
    %th Player
    %th Level
    %th Next exp
    %th Shoot
    %th Dribble
    %th Pass
    %th Block
    %th Tackle
    %th Cut
    %th Speed
    %th Power
    %th Technique
    %th Stamina
    %th Catching
    %th Punching
    %th Offense
    %th Defense
    %th Total point
    %th
    %th
    %th

  - @level_data.each do |level_datum|
    %tr
      %td= level_datum.player_id
      %td= level_datum.level
      %td= level_datum.next_exp
      %td= level_datum.shoot
      %td= level_datum.dribble
      %td= level_datum.pass
      %td= level_datum.block
      %td= level_datum.tackle
      %td= level_datum.cut
      %td= level_datum.speed
      %td= level_datum.power
      %td= level_datum.technique
      %td= level_datum.stamina
      %td= level_datum.catching
      %td= level_datum.punching
      %td= level_datum.offense
      %td= level_datum.defense
      %td= level_datum.total_point
      %td= link_to 'Show', level_datum
      %td= link_to 'Edit', edit_level_datum_path(level_datum)
      %td= link_to 'Destroy', level_datum, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Level datum', new_level_datum_path

app/views/level_data/new.html.haml
%h1 New level_datum

= render 'form'

= link_to 'Back', level_data_path

app/views/level_data/show.html.haml
%p#notice= notice

%p
  %b Player:
  = @level_datum.player_id
%p
  %b Level:
  = @level_datum.level
%p
  %b Next exp:
  = @level_datum.next_exp
%p
  %b Shoot:
  = @level_datum.shoot
%p
  %b Dribble:
  = @level_datum.dribble
%p
  %b Pass:
  = @level_datum.pass
%p
  %b Block:
  = @level_datum.block
%p
  %b Tackle:
  = @level_datum.tackle
%p
  %b Cut:
  = @level_datum.cut
%p
  %b Speed:
  = @level_datum.speed
%p
  %b Power:
  = @level_datum.power
%p
  %b Technique:
  = @level_datum.technique
%p
  %b Stamina:
  = @level_datum.stamina
%p
  %b Catching:
  = @level_datum.catching
%p
  %b Punching:
  = @level_datum.punching
%p
  %b Offense:
  = @level_datum.offense
%p
  %b Defense:
  = @level_datum.defense
%p
  %b Total point:
  = @level_datum.total_point

= link_to 'Edit', edit_level_datum_path(@level_datum)
\|
= link_to 'Back', level_data_path

app/views/players/_form.haml
= form_for(@player) do |f|
  - if @player.errors.any?
    #error_explanation
      %h2
        = pluralize(@player.errors.count, "error")
        prohibited this player from being saved:
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :player_id
    %br/
    = f.text_field :player_id
    %br/
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :short_name
    %br/
    = f.text_field :short_name
  .field
    = f.label :player_team_id
    %br/
    = f.text_field :player_team_id
  .field
    = f.label :name_id
    %br/
    = f.text_field :name_id
  .field
    = f.label :exp_type
    %br/
    = f.text_field :exp_type
  .field
    = f.label :good_position_fw
    %br/
    = f.check_box :good_position_fw
  .field
    = f.label :good_position_mf
    %br/
    = f.check_box :good_position_mf
  .field
    = f.label :good_position_df
    %br/
    = f.check_box :good_position_df
  .field
    = f.label :good_position_gk
    %br/
    = f.check_box :good_position_gk
  .field
    = f.label :player_title
    %br/
    = f.text_field :player_title
  .field
    = f.label :grade_id
    %br/
    = f.text_field :grade_id
  .field
    = f.label :join_comment
    %br/
    = f.text_field :join_comment
  .actions
    = f.submit

app/views/players/edit.html.haml
%h1 Editing player
= render 'form'
= link_to 'Show', @player
|
\#{link_to 'Back', players_path}

app/views/players/index.html.haml
%h1 Listing players
Player Count: 
= @players.count
<br>Level Count:
= @levelcount
%table
  %tr
    %th Player
    %th Name
    %th Player team
    %th Position
    %th Player title
    %th Grade
    %th Max Total
    %th Join comment
    %th
  - @players.each do |player|
    %tr
      %td= link_to player.player_id, player_path(player)
      %td= link_to player.name, players_path(:name => player.name)
      %td= player.teams ? player.teams.name : player.player_team_id
      %td 
        -if player.good_position_fw
          .fw FW 
        -if player.good_position_mf
          .mf MF 
        -if player.good_position_df
          .df DF 
        -if player.good_position_gk
          .gk GK 
      %td= player.player_title
      %td= link_to player.grade.name, players_path(:grade => player.grade_id)
      %td= player.max_level.total_point if player.max_level
      %td= player.join_comment
%br

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.haml
%p#notice= notice
%p
  #player_image
    - if @player.player_id
      = image_tag("player_" + @player.player_id.to_s + ".png")
%table
  %td.player_info
    %p
      %b Player ID:
      = @player.player_id
    %p
      %b Name:
      = @player.name
    %p
      %b Short name:
      = @player.short_name
    %p
      %b Player team:
      = @player.teams ? @player.teams.name : @player.player_team_id
    %p
      %b
        %div{:style => "display:inline"} Position:
      -if @player.good_position_fw
        .fw FW 
      -if @player.good_position_mf
        .mf MF 
      -if @player.good_position_df
        .df DF 
      -if @player.good_position_gk
        .gk GK 
    %p
      %b Player title:
      = @player.player_title
    %p
      %b Grade:
      = @player.grade.name
    %p
      %b Join comment:
      = @player.join_comment
  %td.player_info
    %p
      %b Moves:
      - @player.special_attacks.each do |move|
        %p= link_to move.name, special_attack_path(move)
%p
  %b Levels:
%table
  %tr
    %th Level
    %th Exp/Next
    %th Total
    %th Offense
    %th Shoot
    %th Dribble
    %th Pass
    %th Defense
    %th Block
    %th Tackle
    %th Cut
    %th Speed
    %th Power
    %th Technique
    %th Stamina
    %th Catching
    %th Punching
  - previous_level = 1
  - @player.level_datum.each do |level_data|
    %tr{ "class" => (previous_level / 10 != level_data.level / 10) ? "top_divider" : "" }
      %td= level_data.level
      %td= level_data.next_exp
      %td= level_data.total_point
      %td= level_data.offense
      %td= level_data.shoot
      %td= level_data.dribble
      %td= level_data.pass
      %td= level_data.defense
      %td= level_data.block
      %td= level_data.tackle
      %td= level_data.cut
      %td= level_data.speed
      %td= level_data.power
      %td= level_data.technique
      %td= level_data.stamina
      %td= level_data.catching
      %td= level_data.punching
    - previous_level = level_data.level

= link_to 'Back', players_path

app/views/special_attacks/index.html.haml
%h1 Listing special attacks
Special Attack Count: 
= @special_attack.count
%table
  %tr
    %th ID
    %th Name
    %th Skill Comment
    %th Type
    %th Type (Eng)
    %th Power
    %th Cost
    %th Blows away
    %th
  - @special_attack.each do |special_attack|
    %tr
      %td= link_to special_attack.special_attack_id, special_attack_path(special_attack)
      %td= special_attack.name
      %td= special_attack.skill_comment
      %td= special_attack.attack_type
      %td= special_attack.attack_type_english
      %td= special_attack.power
      %td= special_attack.cost
      %td= special_attack.is_broken
      %td
%br

app/views/special_attacks/show.html.haml
%p#notice= notice
%p
  %b Special Attack ID:
  = @special_attack.special_attack_id
%p
  %b Name:
  = @special_attack.name
%p
  %b Skill Comment:
  = @special_attack.skill_comment
%p
  %b Type:
  = @special_attack.attack_type
%p
  %b Type (English):
  = @special_attack.attack_type_english
%p
  %b Cost:
  = @special_attack.cost
%p
  %b Power:
  = @special_attack.power
%p
  %b Will blow players away:
  = @special_attack.is_broken
%p
  %b Players with this exact special attack (same persona):
  - @special_attack.players.each do |player|
    %p= link_to player.name + " (" + ((player.teams.nil? || player.teams.name.nil? ) ? "" : player.teams.name) + ") (" + player.grade.name + ")", player_path(player)
%p
  %b Players with a special attack with the same name (possibly with a different cost):
  -# @special_attack.with_same_name.each do |attack|
    -# attack.players.each do |player|
      %p=# link_to player.name + " (" + ((player.teams.nil? || player.teams.name.nil? ) ? "" : player.teams.name) + ") (" + player.grade.name + ")", player_path(player)

= link_to 'Back', special_attacks_path